### ISSUE TITLE
Greyscale filter in biggest tissue region is redundant

### ISSUE THREAD

**Issue by nicolebussola** [histolab/histolab#120]
In the composition of filter to segment tissue defined in the _main_tissue_areas_mask_filters property, the greyscale filter is redundant as already performed in the Otsu filter

**Comment by alessiamarcolini** [comment]
The Otsu filter "corrects the user" in case the image is not grayscale, throwing a warning and converting to grayscale. So, I don't think that explicitly converting the image to grayscale is redundant. Otherwise, we would need to live with the warning

**Comment by nicolebussola** [comment]
ur right, my bad
