### ISSUE TITLE
Remove ⚠️ VisibleDeprecationWarning ⚠️ from tiler.py module

### ISSUE THREAD

**Issue by ernestoarbitrio** [histolab/histolab#156]
This line, produces a `VisibleDeprecationWarning` with `python 3.6` ([here](https://travis-ci.com/github/histolab/histolab/jobs/394799740) the travis job reference)
https://github.com/histolab/histolab/blob/7cc6af595056234a011586c823cf78f18601c509/src/histolab/tiler.py#L692

Traceback:
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
    scores_ = np.array(scores)[:, 0]
```

**Task**: Remove this warning and check that each job in CI don't have this warning message anymore

**Comment by TediaN97** [comment]
i would like if u assign me on this issue

**Comment by ernestoarbitrio** [comment]
> i would like if u assign me on this issue

Go for it! Fork the repo, create a new branch and submit a new PR.
Here the contribution guidelines: https://github.com/histolab/histolab/blob/master/CONTRIBUTING.md

**Comment by alessiamarcolini** [comment]
Hi @TediaN97 let us know if you need any help!
