### ISSUE TITLE
Add option to change extraction masks

### ISSUE THREAD

**Issue by alessiamarcolini** [histolab/histolab#158]
Currently, Histolab extracts tiles from the biggest tissue box of the slide (for backward compatibility with previous work).

I'd like to have the possibility to change the area to extract from, for example from the segmented tissue area.

Another cool thing to add could be the possibility for the users to supply their own binary mask for the extraction.

To achieve this, there are two viable options:
1) add a parameter to the extract method of the tilers, like 'mode' or something like this, to control the extraction area. This would be easy and compatible with the previous API, but users must use one of the modes we are providing and cannot implement a custom one
2) provide a different API to provide a mask, either one of the Histolab masks or a custom extraction mask

**Comment by ernestoarbitrio** [comment]
We should get rid of `biggest_tissue_box_mask` property from the `Slide` class and create custom objects that given the Slide return the binary mask according to the algorithm chosen by the user.

```python
class BinaryMaskObj:
	pass

class BiggestTissueBox(_BinaryMaskObj):
	def mask():
		pass

class YetAnotherTissueBox(_BinaryMaskObj):
	def mask():
		pass
```

then within the `extract` method of the `Tiler` we will have a new signature like:

```python
	...
	def extract(slide: Slide, binary_mask_extractor: BinaryMaskObj):
		pass
```
