### ISSUE TITLE
Tilers should control tissue_percent parameter of has_enough_tissue

### ISSUE THREAD

**Issue by alessiamarcolini** [histolab/histolab#163]
At the moment, the user can only decide whether to apply the tissue check during tile extraction or not, and not decide the percentage of tissue required. 

We should add another parameter `tissue_percent` to the tilers' constructor to be used during the `has_enough_tissue` check

**Comment by ernestoarbitrio** [comment]
@alessiamarcolini can you give more details about this issue? I'd like to work on that but I don't have enough knowledge to go through this😅

**Comment by alessiamarcolini** [comment]
@ernestoarbitrio 
a `Tile` has the method `has_enough_tissue`, which can be parametrized via the`tissue_percent` parameter. REF: https://github.com/histolab/histolab/blob/master/src/histolab/tile.py#L78

a `Tiler` calls that method (if `check_tissue=True`) when deciding whether to save the tile or not. REF: https://github.com/histolab/histolab/blob/master/src/histolab/tiler.py#L282

The `Tiler` uses the method with its default parameters, so there is no way for the user to specify, let's say, that 50% of tissue is enough to save the tile.

I'd like to add a new parameter to the tilers' constructor `tissue_percent` to be able to control that behavior
