### ISSUE TITLE
Add "verbose" level argument in "GridTiler.extract" method

### ISSUE THREAD

**Issue by lorenz-gorini** [histolab/histolab#228]
**Is your feature request related to a problem? Please describe.**
I am extracting tiles by using a `GridTiler` while looping over the slides from a `SlideSet`.
Therefore the `GridTiler.extract` method is printing many messages (~12000 per WSI) like:
```bash
Tile 998 saved: 8469_tile_998_level0_3245_12345_345_12445.png
```
This means that I am not able to read the messages that I print within my script (when reading a new WSI, when an error occurs, the extracted tile count, ...)

**Describe the solution you'd like**
I would love to be able to set the verbosity level of  `GridTiler.extract` method  in order for it to stop printing many messages that fill up the standard output.

**Describe alternatives you've considered**
I could also redirect the standard output to a log file while extracting tiles, but I should still look for the error messages

**Additional context**

**Comment by ernestoarbitrio** [comment]
Thanks @lorenz-gorini -- Speaking of this, printing stuff is not something more efficient for coding. Anyway i think your hunch is absolutely legit. I'll take care of this pivoting the print statement into a logger statement, and so we can set the verbosity level.
