### ISSUE TITLE
General locate_mask method of BinaryMask

### ISSUE THREAD

**Issue by alessiamarcolini** [histolab/histolab#245]
As of now, we have a `locate_biggest_tissue_box ` method of `Slide` to create an image with the contour of the biggest tissue box mask superimposed on the slide thumbnail (or the tissue mask): https://github.com/histolab/histolab/blob/0f0c18c2b43a5b993674323f6eda2b7b50f53a23/src/histolab/slide.py#L151-L157

It would make sense to have a general mechanism to create such images working with all the binary masks. 

Therefore, I propose to have a method of `BinaryMask` which internally gets the result of the call on `_mask(slide)` and draws the polygons corresponding to the regions where the binary mask is `1` on the slide thumbnail (or on the mask directly).

I'm not entirely sure how to implement this but maybe this could help: https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.find_contours

**Comment by alessiamarcolini** [comment]
Given
```python
from histolab.data import heart_tissue
from histolab.masks import BiggestTissueBoxMask
from histolab.slide import Slide
binary_mask = BiggestTissueBoxMask()
f, path = heart_tissue()
slide = Slide(path, "pp")
```

which option is better?
**1**:
 ```python
im = binary_mask.locate_mask(slide)
```

**2**: 
```python
im = slide.locate_mask(binary_mask)
```

I would go for option 2. @ernestoarbitrio @nicolebussola ?

**Comment by ernestoarbitrio** [comment]
I vote 2
