### ISSUE TITLE
LocalOtsuThreshold wrong type

### ISSUE THREAD

**Issue by nicolebussola** [histolab/histolab#255]
The LocalOtsuThreshold filter (image_filter) is defined as "branch filter" and thus stated that it returns a masked array. However the corresponding functional returns a PIL Image (as it should be). This filter needs to be moved among the filters returning a PIL Image.

**Comment by alessiamarcolini** [comment]
@nicolebussola are you sure that it should return a PIL image? the `LocalOtsuThreshold` filter is just a modification of the `OtsuThreshold` filter, which is returning a np array. Therefore I think `LocalOtsuThreshold` should return an array as well.

**Comment by nicolebussola** [comment]
yup but the otsu threshold is returning a binary mask, the local otsu returns an array with the local thresholds... I am not sure it's best to return an array here

**Comment by alessiamarcolini** [comment]
I guess we should transform the local thresholds to a mask as they are doing it here in the tutorial https://scikit-image.org/docs/0.12.x/auto_examples/segmentation/plot_local_otsu.html with our function `util.threshold_to_mask` and then return this mask... what do you think?

**Comment by nicolebussola** [comment]
In the tutorial they return the output of local otsu that is a mask (not binary). By applying our util function we would transform it to a binary mask, but it is not the goal here. I think the output is okay as it is, we just need to decide whether return it as an array or as an image, I would probably go with the image

**Comment by alessiamarcolini** [comment]
alright let's go with the image. can you do it?

**Comment by nicolebussola** [comment]
sure
