### ISSUE TITLE
Apply [NucleiScorer] to images (tiles) directly

### ISSUE THREAD

**Issue by duernaT** [histolab/histolab#265]
Thank you for this wonderful tool.

I have a question about the  `[NucleiScorer]` function.
Can I get the` [NucleiScorer]` from one image (HE-stained histology picture)? [like .png, .tiff, and so on, not WSI].

The reason I want to do so is that I have a lot of pictures (lots of nuclei, medium nuclei, and fewer nuclei, ), and I wondered if I could classify those images based on the `NucleiScorers`.

Thank you.
Duerna

**Comment by alessiamarcolini** [comment]
Hey @duernaT, thank you for your question 🙌

Our `NucleiScorer` is meant to be used to estimate the presence of nuclei starting from a `Tile` object (a patch), not from a `Slide` (representing a WSI). 

It is easy to wrap a `.png` file (for example, or any file format that `PIL` can open **) in a `Tile` and then use the scorer:

```python
from histolab.tile import Tile
from histolab.scorer import NucleiScorer
from PIL import Image

image = Image.open("/path/to/image")
tile = Tile(image, None, None)
nuclei_scorer = NucleiScorer()

score = nuclei_scorer(tile)
```
** please note, however, that the sequence of filters used by this scorer has been designed to work well with small images representing regions of interest, not with big images where the nuclei are not clearly visible.

Please let me know if I answered your question or if you have more 🙏 

Cheers,
Alessia

**Comment by duernaT** [comment]
Thank you so much! @alessiamarcolini 
It works perfectly, and I (a beginner of Python) wrote a function to progress my images in a given folder.

Like this:

```
def score_detect(imgs): 
    for image_name in files:
        if ".png" in image_name:
            img = Image.open(image_name)
            tile = Tile(img, None, None)
            nuclei_scorer = NucleiScorer()
            score = nuclei_scorer(tile)
            print(image_name,score)        
    return
```
Very nice function!!!

With many thanks,
Duerna
