### ISSUE TITLE
locate biggest tissue box cannot correctly locate.

### ISSUE THREAD

**Issue by jasnei** [histolab/histolab#273]
please check below image for the result using histolab to create tiles, but I think your code in BiggestTissueBoxMask class could only find the tissue which slide have only 1 region.  But actually at work many slide lis 

![image](https://user-images.githubusercontent.com/52853052/122856819-10555300-d34a-11eb-84ee-e7aa10814056.png)

in the following image I will show that I could find the right biggest region in such type slide.

![image](https://user-images.githubusercontent.com/52853052/122857072-7e9a1580-d34a-11eb-81e4-3a096a322ca6.png)

What do i do to find this region?
1, i done all the same as you guy did
2, find the biggest region first and get all the points
3, find the second biggest region and get all the points ( you may delete the biggest first, the try to find the biggest again, recursive, but only twice) 
4, stack all the point of two regions to get the biggest rectangle box coordinate
![image](https://user-images.githubusercontent.com/52853052/122857492-244d8480-d34b-11eb-88c7-8320afc8ac81.png)

I'm not sure if it's help, but I just send it.

Best Regards
Albert

**Comment by alessiamarcolini** [comment]
Dear @jasnei, thank you for reaching out.

You are using the `BiggestTissueBoxMask`, and as the documentation says (at https://histolab.readthedocs.io/en/latest/tissue_masks.html#biggesttissueboxmask):
`The BiggestTissueBoxMask keeps only the largest connected component of the tissue, and returns the bounding box including that region`

Therefore, if you want to extract the tiles from all the tissue regions, I suggest you to use the `TissueMask`.
However, if you want to extract the tiles from the *two* biggest regions (or using an even fancier logic) you have to implement your own `BinaryMask` (as illustrated here https://histolab.readthedocs.io/en/latest/tissue_masks.html#custom-mask).

Please let us know if you need further help or if you have any more questions.

Best,
Alessia

**Comment by jasnei** [comment]
> Dear Alessia
> 

Thank you for your reply. 

I already done my own implement. 

Hope you guy could do better. 

Best regards
Albert
