### ISSUE TITLE
Tile Entire WSI

### ISSUE THREAD

**Issue by Payden-McBee** [histolab/histolab#279]
I know that for efficiency, the software automatically detects the tissue region with the largest connected area and crops the tiles within this field. Is it possible to run the tiling on the entire WSI, and not just the largest connected tissue region? 
I would like to use all of the tissue in the WSI, and not just the largest region. The largest region may not be the most informative, particularly when a disease doesn't present uniformly throughout the tissue. Thanks!

**Comment by alessiamarcolini** [comment]
Hi @Payden-McBee, thank you for your question!

The desired behavior is implemented by the `TissueMask` mask, which you can pass to the `Tiler`'s `extract` method. The default is the `BiggestTissueBoxMask`, as you described.
Have a look here https://histolab.readthedocs.io/en/latest/tissue_masks.html for the full example 😄 

Let us know if you have any more questions (or feel free to close the issue if everything is good)

Best,
Alessia

**Comment by Payden-McBee** [comment]
That's spot on. Thanks!
