### ISSUE TITLE
How would I add a scale bar to images?

### ISSUE THREAD

**Issue by afvrbanac** [histolab/histolab#292]
Hello, novice user here with some basic questions. I'm using histolab to extract random tiles at different levels. Is it possible to automatically add a scale bar to these images? 

Also, is the magnification of each level the original magnification divided by the downsample for the level? So for example, for a 40X image at level 0, if the downsample for level 2 was 16, the magnification would be 2.5X?

**Comment by ernestoarbitrio** [comment]
Hi @afvrbanac I will transfer this issue in a github discussion!!! 😄
