### ISSUE TITLE
Better upsampling and downsampling modes

### ISSUE THREAD

**Issue by kheffah** [histolab/histolab#302]
Currently, the upsampling and downsampling mode is BILINEAR. Generally-speaking, it would be better to use BICUBIC for upsampling and LANCZOS for downsampling. (See [this](https://pillow.readthedocs.io/en/stable/releasenotes/2.7.0.html?highlight=resize#image-resizing-filters)). 

Currently, [these two lines](https://github.com/histolab/histolab/blob/support-mpp/src/histolab/slide.py#L44-L45) control this behavior. But many of the test expectations were saved using the BILINEAR method so this will require saving new expectations.

**Comment by alessiamarcolini** [comment]
Hey @kheffah, thank you for noticing this! 

> Generally-speaking, it would be better to use BICUBIC for upsampling and LANCZOS for downsampling. 

Honestly I didn't know 👀 

From my side we can proceed and fix this 👍

**Comment by kheffah** [comment]
@alessiamarcolini Awesome. I mean, it's not a rule .. just what tends to look better and have less artifacts etc. BTW, I recommend branching off `support-mpp`` branch since it parametrized this behavior in the two lines linked above. Cheers!
