### ISSUE TITLE
pixel_overlap not work in GridTiler

### ISSUE THREAD

**Issue by nipeone** [histolab/histolab#370]
**Describe the bug**
1.i have set "pixel_overlap" to 64 in GridTiler,but it seemingly does not work。adjacent tiles have no overlapping area.
2.if i set check_tissue to True, only a few tiles can be generated.

**To Reproduce**

    class CustomTissueMask(TissueMask):
        def __init__(self, scale_factor=32):
            self.scale_factor = scale_factor

        def _mask(self, slide):
            img = slide.scaled_image(self.scale_factor)
            filters = FiltersComposition(Slide).tissue_mask_filters
            mask = filters(img)
            return mask
    grid_tiles_extractor = GridTiler(
        tile_size=(512, 512),
        level=0,
        check_tissue=False, # default
        pixel_overlap=64, # default
        prefix="grid/", # save tiles in the "grid" subdirectory of slide's processed_path
        suffix=".png" # default
        )
    thumb = grid_tiles_extractor.locate_tiles(
        slide=slide,
        extraction_mask=CustomTissueMask(),
        scale_factor=32,
        alpha=200,
        outline="#046C4C",
    )
    thumb.save("./tmp/1900991B_grid_thumb.png")
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4449628/147375848-d21e4947-a9a0-45ba-9a92-ebb7927ce192.png)

**Software (please complete the following information):**
 - OS: ubuntu
 - Python Version:  3.8
 - histolab version: 0.4.1

**Additional context**
if i change source code in tiler.py like below, i can get desired result.
![image](https://user-images.githubusercontent.com/4449628/147375895-99b71261-4d43-4316-a659-6930f1794b51.png)

desired result:
![image](https://user-images.githubusercontent.com/4449628/147375928-d90395fd-b007-4ea1-af7d-a776c9ef5d6c.png)

**Comment by ernestoarbitrio** [comment]
Hi @nipeone thanks for reporting this. We are investigating :D

**Comment by ernestoarbitrio** [comment]
Hi @nipeone we confirm that this is a bug and your solution in the screenshot posted is the actual solution. Do you wanna open a new PR and give a contribution to histolab? Let us know ❤️ 
Thanks again 😉

**Comment by nipeone** [comment]
if i create new PR,should i create unit test about pixel overlap?

**Comment by ernestoarbitrio** [comment]
> @ernestoarbitrio with pleasure！but if i create new PR,need i create unit test about this issue?

ehm yes you do, but if you have problems on that me or @alessiamarcolini can add a commit to your PR or we can chat a bit and we can explain how to provide a test
