### ISSUE TITLE
Calling locate_tiles with a GridTiler on level 1, produce a grid with missing rows.

### ISSUE THREAD

**Issue by bguetarni** [histolab/histolab#381]
**Describe the bug**
While visualizing the results of the GridTiler tiling, it happened that calling the method `locate_tiles` with a GridTiler object that has been constructed with `level=1` can produce a tiling that miss one row out of two (see Slide 1 - level 1). This problem happened on several slides. What is even more confusing, is that when I use `level=2` instead of 1, the tiling is done correctly (see Slide 1 - level 2).

However, this is not systematic, I have lots of slides that do not happen to produce that problem (the tiling is really a grid; see Slide 2 - level 1); 

**To Reproduce**
1. Load a slide.
2. Creates a GridTiler object with `level=1`.
3. Call `locate_tiles` and visualize the result.
4. Repeat with a GridTiler object with `level=2/3/+` on the same slide.

You can get the Slide 1 [here](https://drive.google.com/file/d/1dUP_aS9GSfwDbnhJKEWIBo5po0lb0xXM/view?usp=sharing).

**Expected behavior**
The grid should not have missing rows.

**Screenshots**
Slide 1 - level 1
![télécharger (10)](https://user-images.githubusercontent.com/43996514/151780027-fa681c69-9420-4ae7-a93a-8908154a0976.png)

Slide 1 - level 2
![télécharger (9)](https://user-images.githubusercontent.com/43996514/151780078-2a5c332c-d92e-4b56-8236-06992c3cfc05.png)

Slide 2 - level 1
![télécharger (12)](https://user-images.githubusercontent.com/43996514/151780103-77802174-d929-4d1c-bc00-8e9436cbaec7.png)

**Software (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - histolab version: 0.4.1
 - openslide-python version: 1.1.2

**Additional context**
None

**Comment by alessiamarcolini** [comment]
Dear @bguetarni, sorry for the late response.
The issue here might be rooted in the same issue as the one in issue #295, but I cannot check as the slide you were using is not available anymore. Could you upload it again and let me know?

**Comment by bguetarni** [comment]
@alessiamarcolini, Thank you for your response.
I uploaded the slide, it's available through the link of my first post but I add it [here](https://drive.google.com/file/d/1dUP_aS9GSfwDbnhJKEWIBo5po0lb0xXM/view?usp=sharing).
