### ISSUE TITLE
inconsistent behaviour of TissueMask

### ISSUE THREAD

**Issue by vladpopovici** [histolab/histolab#385]
**Describe the bug**
TissueMask produces different results, depending on whether or not __large_image__  is used when reading the slide. I have tested this behaviour with 2 different slide formats (.mrxs and .svs).

**To Reproduce**
See attached screenshot.

**Expected behavior**
The mask returned by TissueMask should be the same (or very close), independent of the backend used for reading the slides. This should be the case for all methods.

**Screenshots**
![Screenshot_2022-02-21_13-43-34](https://user-images.githubusercontent.com/9034346/154957636-248c61dc-9d48-40fa-be19-9c39167af32b.png)

**Software (please complete the following information):**
 - OS: Linux
 - Python Version: 3.9
 - histolab version: 0.4.1
 - large_image: 1.11.1
 - pixman: 0.40.0
 
**Additional context**
Several other issues were triggered depending on the backend:
 - When opening an .MRXS file, the background of the slides is different depending on whether large_image is used or not. In the former case, the background is black, while in the latter is white. This is probably due to the way OpenSlide and large_image handle the alpha-channel from the .MRXS: using it as a mask to set background to white or simply ignoring it.
 - (as a consequence of the above) TissueMask returns completely different results in the two use cases.
 - In the case of the .SVS file, the thumbnail image has different size depending on which backend was used.

**Comment by alessiamarcolini** [comment]
Dear @vladpopovici, thank you for spotting this silly bug!!

This has to do with the fact that we calculate the binary mask on the slide's thumbnail.

and ATM, in `Slide.thumbnail`, if we retrieve it from OpenSlide, we specify the desired thumbnail dimension; if we retrieve it from large_image we don't (and there is probably some default value there)! 
REF: https://github.com/histolab/histolab/blob/master/histolab/slide.py#L500

So a fix for this will come ASAP 🚀
