### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by bguetarni** [histolab/histolab#407]
**Describe the bug**
I think I spotted a small mistake in the description of the function `Slide._thumbnail_size()`, line 680 :

` \big(\frac{v}{10^{w-2}},\frac{ v }{10^{n-2}}\big) `

the second part should be ` \frac{m}{10^{n-2}}\big) `

**Expected behavior**

` \big(\frac{v}{10^{w-2}},\frac{m}{10^{n-2}}\big) `

according to line 663. :
` If the size of the slide is (v, m) where v has magnitude w and m has magnitude n `

**Comment by alessiamarcolini** [comment]
Hi @bguetarni, thank you for opening this issue!

@nicolebussola could you have a look please?
