### ISSUE TITLE
Score a slide according to attention matrix

### ISSUE THREAD

**Issue by CaiYitao** [histolab/histolab#540]
Could we score a slide according to the attention matrix produced by a trained neural network, for example, a multihead attention or transformer model?

**Comment by alessiamarcolini** [comment]
Dear @CaiYitao thank you for your question!

We designed the `ScoreTiler` in a way to make it easy to score tiles according to different needs, and it is exactly what the `Scorer` implements (which is then passed to the `ScoreTiler`)

A `Scorer` can be any class with a `__call__` method that takes in a `Tile` object and returns a float

So in your case I'd suggest to subclass the `Scorer` class and implement a custom `__call__` method to feed the `Tile` object to the neural network and then find a way to compute a float from the output

**Comment by CaiYitao** [comment]
Thank you @alessiamarcolini for your prompt reply. 
Can the `Scorer`  return an array of floats?  cause The attention matrix is of size:  number of tiles by number of classes. so for each tile, it is a 1d float array of the size of the number of classes.

**Comment by alessiamarcolini** [comment]
It cannot, in the end each tile must be associated with one single number so they can be sorted accordingly. Can you find a way to reduce this array to one value?

**Comment by CaiYitao** [comment]
Thank you very much for your notice, maybe I can try to do it for each class, for example, if there are 2 classes, then we can produce two score maps.
