### ISSUE TITLE
How to get Tissue mask as binary numpy array?

### ISSUE THREAD

**Issue by YemanBrhane** [histolab/histolab#591]
In the documentation of the TissueMask() class, it is mentioned the return type is nd.array. But the the output of TissueMask() function is of __class__  is "<class 'histolab.masks.TissueMask'>".

I created the mask as follows:

mask = TissueMask(
   RgbToGrayscale(),
   OtsuThreshold(),
   ApplyMaskImage(slide.thumbnail), # slide is histolab slide object
   GreenPenFilter(),
   RgbToGrayscale(),
   Invert(),
   OtsuThreshold(),
   RemoveSmallHoles(),
   RemoveSmallObjects(),
)

Is there a way to get the mask as numpy array.

I have tried the following ways:

1. PIL.Image.fromarray(mask). This generated "AttributeError: 'TissueMask' object has no attribute '__array_interface__'"
2. . np.ndarray(mask) This generated "TypeError: expected sequence object with len >= 0 or a single integer"

It will be great if there is a way to get the mask as nd.array or numpy so that users can save it, visualise it and make modification locally.

**Comment by alessiamarcolini** [comment]
Hi @YemanBrhane thank you for opening this issue!

The `TissueMask` is an object that defines the type of filters to apply to a `Slide`. So to obtain the actual binary mask related to a `Slide`, you need to use the `__call__` method of the `TissueMask` instance on the `Slide` instance.

For example,

```python
mask = TissueMask(
RgbToGrayscale(),
OtsuThreshold(),
ApplyMaskImage(slide.thumbnail), # slide is histolab slide object
GreenPenFilter(),
RgbToGrayscale(),
Invert(),
OtsuThreshold(),
RemoveSmallHoles(),
RemoveSmallObjects(),
)

slide = Slide("path/to/slide", "path/to/processed")

binary_mask: np.ndarray = mask(slide)
```

the `binary_mask` will be then a numpy array.

Please let me know if this clarifies it, and feel free to close this issue if so :)

**Comment by YemanBrhane** [comment]
Thank you for the quick response. This solved the issue.
