### ISSUE TITLE
Why there are a lot of blank areas even if I set the tissue_percent to 80.00?

### ISSUE THREAD

**Issue by a1ecbennington** [histolab/histolab#695]
I'm trying to extract some WSI tiles, but there are a lot of blank areas even if I set the tissue_percent to 80.00. I'm using histolab 0.3.0 on Windows11.
![image](https://github.com/histolab/histolab/assets/103823592/d5a6c2ce-2ee8-4bfb-8c2d-9a9371059072)
The code is 
import os
import histolab.tiler as tiler
from histolab.slide import Slide

def extract_patient_id(filename):
    parts = filename.split('-')
    patient_id = parts[0]
    return patient_id

def get_tile(filename):
    tiles_extractor = tiler.GridTiler(
        tile_size=(512, 512),
        level=0,
        check_tissue=True,
        tissue_percent=80.0,
        prefix=filename + '/',
        suffix=".png"
    )
    processed_path = "E:/Tiles"
    image = Slide(files_directory + '/' + filename, processed_path)
    tiles_extractor.extract(image)
    return

files_directory = "E:/Slides"
data_list = []

for filename in os.listdir(files_directory):
    if filename.endswith(".ndpi"):
        get_tile(filename)

**Comment by ernestoarbitrio** [comment]
I think histolab 0.3.0 is quite old and can be buggy. First things first I'd update the version and re-try it. Let us know please

**Comment by a1ecbennington** [comment]
> I think histolab 0.3.0 is quite old and can be buggy. First things first I'd update the version and re-try it. Let us know please

Sorry, I'm using on Windows11 and higher versions don't support it. I will try it on Ubuntu. Thank you.

**Comment by a1ecbennington** [comment]
> Yes better try on a different system than windows :D

![image](https://github.com/histolab/histolab/assets/103823592/49c6fda2-8484-4d17-a387-2895ee11a09d)
I tried it on my Ubuntu on VMware, but there are still many blanks. The python version is 3.8 and the histolab is 0.7.0
And the code is 
import os
import histolab.tiler as tiler
from histolab.slide import Slide


def extract_patient_id(filename):
    parts = filename.split('-')
    patient_id = parts[0]
    return patient_id


def get_tile(filename):
    tiles_extractor = tiler.GridTiler(
        tile_size=(512, 512),
        level=0,
        check_tissue=True,
        tissue_percent=80.0,
        suffix=".png"
    )
    processed_path = "/media/liuhongxing/固态移动硬盘/test1"
    image = Slide(filename, processed_path)
    tiles_extractor.extract(image)
    return


file_name = "/media/liuhongxing/固态移动硬盘/F155519-1.ndpi"
get_tile(file_name)

**Comment by alessiamarcolini** [comment]
Hi @a1ecbennington :)

The `GridTiler.extract` method has an `extraction_mask` parameter, that defines the binary mask from where to extract the tiles --> https://histolab.readthedocs.io/en/latest/api/tiler.html#histolab.tiler.GridTiler.extract
The default is the `BiggestTissueBoxMask` object, which defines the box containing the largest contiguous tissue area --> https://histolab.readthedocs.io/en/latest/api/masks.html

So what you describe is actually the expected behaviour. Try using an instance of the `TissueMask` for the `extraction_mask` parameter instead, that is probably what you want :)

**Comment by a1ecbennington** [comment]
> Hi @a1ecbennington :)
> 
> The `GridTiler.extract` method has an `extraction_mask` parameter, that defines the binary mask from where to extract the tiles --> https://histolab.readthedocs.io/en/latest/api/tiler.html#histolab.tiler.GridTiler.extract The default is the `BiggestTissueBoxMask` object, which defines the box containing the largest contiguous tissue area --> https://histolab.readthedocs.io/en/latest/api/masks.html
> 
> So what you describe is actually the expected behaviour. Try using an instance of the `TissueMask` for the `extraction_mask` parameter instead, that is probably what you want :)
Yes, it is working. Thank you very much!
