### ISSUE TITLE
Installation error using pip 

### ISSUE THREAD

**Issue by qasimgilani** [histolab/histolab#706]
Hi,

I am receiving this installation error "

```
Building wheels for collected packages: scikit-image
  Building wheel for scikit-image (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-image (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [626 lines of output]
      setup.py:9: DeprecationWarning:

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image, which is required to install pyproject.toml-based projects
```

how can I resolve this issue? Your help will be appreciated.

**Comment by alessiamarcolini** [comment]
Hi @qasimgilani which Python version are you using?

**Comment by qasimgilani** [comment]
Hi Alessia,

I am using the Python 3.11.5 version.

**Comment by qasimgilani** [comment]
Hi Alessia,

I was able to install Histolab after creating new conda environment with Python 3.10, but now I am getting a new error 
`
OSError: libopenslide.so.0: can not open shared object file: No such file or directory.`

**Comment by qasimgilani** [comment]
I removed this error by installing histolab in a new conda environment with Python 3.10.
