### ISSUE TITLE
Openslide-python on PyPI is broken

### ISSUE THREAD

**Issue by alessiamarcolini** [histolab/histolab#73]
**Describe the bug**
Installing openslide-python from PyPI is not possible right now: https://github.com/openslide/openslide-python/pull/76

We should make it installable from git

**Comment by alessiamarcolini** [comment]
Fixed in #76

**Comment by leouieda** [comment]
@alessiamarcolini I noticed that openslide is on conda-forge, which might make it easier for your users: https://github.com/conda-forge/openslide-feedstock

Only drawback is that they don't have Windows builds but it might not be too hard to add it. If this is useful for you, consider opening an issue there (someone might be able to help). 

I'm also not sure if they only package the C library or if the Python bindings are included.

**Comment by alessiamarcolini** [comment]
Hi @leouieda, thanks for your comment, but _that_ OpenSlide is only the C library. Here the problem is openslide-python on PyPI (see the PR link in the first comment)

**Comment by leouieda** [comment]
Ah right, sorry about that.
